# Generated by Django 2.0.7 on 2018-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=16)),
                ('tag_header', models.CharField(max_length=32)),
                ('goto', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=64)),
                ('header', models.TextField()),
                ('six_fifty', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
