# Generated by Django 2.0.7 on 2018-07-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='goto',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag_header',
        ),
    ]
